# Generated by Django 4.2.4 on 2023-08-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_user_alter_review_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='url',
            new_name='website',
        ),
    ]
