# Generated by Django 4.2.4 on 2023-09-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_business_user_review_user_alter_category_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
